  - name: Installing Node using npm
    become: yes
    hosts: nexus_server
    tasks:
      - name: Updating apt 
        apt:
          update_cache: yes
          force_apt_get: yes
          cache_valid_time: 3600
      - name: Installing Java openJDK version 8
        apt: name=openjdk-8-jre-headless
      - name: Installing net-tools
        apt: name=net-tools

  - name: Download and Unpack Nexus Installer 
    become: yes
    hosts: nexus_server
    tasks:
      - name: Checking nexus stats
        stat:
          path: /opt/nexus
        register: stat_result


      - name: Downloading . . .
        get_url:
          url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz    
          dest: /opt/    
        register: download_result

      - name: Unpacking . . .
        unarchive:
          remote_src: true
          src: "{{download_result.dest}}"
          dest: /opt/
        when: not stat_result.stat.exists 

      - name: Finding The nexus Folder inside /opt and storing the final result 
        find: 
          paths: /opt/
          patterns: "nexus-*"
          file_type: directory
        register: file_result

      - name: Renaming nexus folder
        shell: mv {{file_result.files[0].path}} /opt/nexus
        when: not stat_result.stat.exists 
      
      
  - name: Create new User named nexus
    hosts: nexus_server
    become: yes
    tasks: 
    - name: Create nexus group
      group:
        name: nexus
        state: present
    - name: Create nexus user with /bin/bash default shell and group nexus 
      user:
        name: nexus
        comment: "nexus user"
        group: nexus
        shell: /bin/bash
    - name: Changing The Ownership of nexus folder to be with nexus user
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Changing The Ownership of sonatype folder to be with nexus user
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

  - name: Start nexus using nexus user
    hosts: nexus_server
    become: yes
    become_user: nexus
    tasks:
      - name: Setting Nexus Configuration to run as nexus user (sun_as_user = nexus) inside nexus.rc file 
        blockinfile:
          path: /opt/nexus/bin/nexus.rc
          block: |
            run_as_user="nexus"
        # lineinfile:
        #   path: /opt/nexus/bin/nexus.rc
        #   regex: '^#run_as_user=""'
        #   line: run_as_user="nexus"
      - name: Starting the nexus server
        command: /opt/nexus/bin/nexus start
  
  - name: Verify Nexus Running 
    hosts: nexus_server
    tasks:
      - name: Check with ps
        shell: ps aux | grep nexus
        register: ps_state
      - debug: msg={{ps_state.stdout_lines}}

      - name: waiting 1 min
        pause:
            minutes: 1

      - name: Check with netstat
        shell: netstat -lnpt
        register: net_state
      - debug: msg={{net_state.stdout_lines}}
